# Problem 1

In [10]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin

import numpy as np
m = np.random.randint(0,10,(5))
print(m)
print("Matrisin boyutu",m.shape)
print("Matrisi boyutlandır:",m.reshape(1,5))
print("Matrisin boyut sayısı:",m.ndim)

[9 6 6 9 6]
Matrisin boyutu (5,)
Matrisi boyutlandır: [[9 6 6 9 6]]
Matrisin boyut sayısı: 1


# Problem 2

In [19]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin
import numpy as np
n =np.arange(1,10,2)
print(n)
a,b,c= np.split(n,[2,4])
print(a)
print(b)
print(c)
print("Parçaları birleştirelim: ", np.concatenate([a,b,c]))

2

[1 3 5 7 9]
[1 3]
[5 7]
[9]
Parçaları birleştirelim:  [1 3 5 7 9]


# Problem 3

In [36]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.random.choice(np.arange(5, 101, 2), size=10)
print(a)
# 2 - matris'in özelliklerini inceleyin
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)
print("Matrisin boyut sayısı:", a.ndim)
print("en buyuk deger:", np.max(a))
print("en kucuk deger: ", np.min(a))
print("ortalama: ", np.mean(a))
print("Küçükten büyüğe sıralama:", np.sort(a))
print("Yeniden boyutlandır:", a.reshape(2,5))

[97 79 57 57 89 17 29 99 13 51]
Shape: (10,)
Size: 10
Data type: int32
Matrisin boyut sayısı: 1
en buyuk deger: 99
en kucuk deger:  13
ortalama:  58.8
Küçükten büyüğe sıralama: [13 17 29 51 57 57 79 89 97 99]
Yeniden boyutlandır: [[97 79 57 57 89]
 [17 29 99 13 51]]
